services:
  rsyslog:
    image: kyzersose/syslog:latest
    container_name: syslog-server
    restart: always
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./logs:/var/log
    environment:
      - TZ=America/Chicago

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./logs:/var/log  # Mount syslog logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
