services:
  rsyslog:
    image: kyzersose/syslog:arm64
    container_name: syslog-server
    restart: always
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./logs:/var/log
    environment:
      - TZ=America/Chicago

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
    secrets:
      - grafana_admin_password

secrets:
  grafana_admin_password:
    file: ./grafana_admin_password.txt

volumes:
  loki_data:
    driver_opts:
      type: none
      device: ./loki
      o: bind,uid=10001,gid=10001